name: Build & Test

on:
  push:
    branches: [ 15.0-develop]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Build with ncc
        run: |
          npm install
          npm run build

      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repo: gaganamadival/openg2p-packaging
          workflow: OpenG2P Odoo Package Dockers build
          ref: 15.0-develop
