name: Trigger OpenG2P Packaging Workflow

on:
  push:
    branches: [ 15.0-develop ]
      workflow_dispatch:

jobs:
  trigger-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repo: gaganamadival/openg2p-packaging
          workflow: OpenG2P Odoo Package Dockers build
          ref: 15.0-develop
