name: Trigger OpenG2P Packaging Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: set variables
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
      - name: Trigger workflow in another repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/gaganamadival/openg2p-packaging/dispatches" \
            -d '{"event_type": "trigger-packaging", "client_payload": {"packageName": "${{ env.BRANCH_NAME }}"}}'
