name: Trigger OpenG2P Packaging Workflow

on:
  push:
  workflow_dispatch:

jobs:
  trigger-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: set variables
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
      - name: Invoke workflow in another repo with inputs
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          github_token: ${{ secrets.PAT }}
          owner: gaganamadival
          repo: openg2p-packaging
          workflow_file_name: package_docker.yml
          client_payload: "{\"packageName\": \"${{ env.BRANCH_NAME }}\"}"
