name: Trigger OpenG2P Packaging Workflow

on:
  push:
    branches:
      - 15.0-develop

jobs:
  trigger-packaging:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: gaganamadival/openg2p-packaging
          workflow: package_docker.yml
          inputs: '{ "packageName": "15.0-develop" }'
