name: pre-commit

on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Get python version
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit|${{ env.PY }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: |
          if [ ! -d ~/.npm ]; then
            npm config set cache ~/.npm;
          fi
          npm install -g npm@8
          pre-commit run --all-files --show-diff-on-failure --color=always

      - name: Check that all files generated by pre-commit are in Git
        run: |
          newfiles="$(git ls-files --others --exclude-from=.gitignore)"
          if [ "$newfiles" != "" ] ; then
              echo "Please check-in the following files:"
              echo "$newfiles"
              exit 1
          fi
